# Copy this file into /secrets/jellyseer-secrets.yaml and filled API keys
#
# mkdir secrets
# cp jellyseer-secrets.template.yaml secrets/jellyseer-secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: jellyseerr-secrets
  namespace: media
type: Opaque
stringData:
  jellyfin-api-key: "jellyfin-api-key-here"
  sonarr-api-key: "sonarr-api-key-here"
  radarr-api-key: "radarr-api-key-here"
