# Copy this file into /secrets/jellyseer-secrets.yaml and filled API keys
#
# mkdir secrets
# cp transmission-secrets.template.yaml /secrets/transmission-secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: transmission-secrets
  namespace: media
type: Opaque
stringData:
  user: "username-here"
  password: "password-here"
